global:
  scrape_interval: 8s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 8s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "job-prometheus"
    scrape_interval: 9s
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "job-node-exporter"
    scrape_interval: 9s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "blackbox_exporter"
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets: ["127.0.0.1:80"]
        labels:
          location: "64 ATIS Sta.36-9+500 (IN)"
          device_name: "Test"
          device_id: "1"

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
